### ISSUE TITLE
Invalid certificate at pinitto.me

### ISSUE THREAD

**Issue by jekuno** [pinittome/pinitto.me#136]
https://pinitto.me/ cannot be accessed. Firefox complains about an invalid certificate (SEC_ERROR_EXPIRED_CERTIFICATE).
An exception for allowing invalid certificates cannot be added to the browser due to HTTP Strict Transport Security (HSTS).

**Comment by lloydwatkin** [comment]
Fixed, apologies, required a letsencrypt upgrade :)

**Comment by jekuno** [comment]
That was fast! Thanks! :)
