### ISSUE TITLE
Extract website 

### ISSUE THREAD

**Issue by lloydwatkin** [pinittome/pinitto.me#65]
Pinitto.me should be the board application only and not the related website stuff so people can run their own versions.

I've created http://go.pinitto.me where we can put website stuff. This needs themeing to match the site and then the content moved from http://pinitto.me to this site.

We should then strip the number of pages on http://pinitto.me down to the bare minimum.

**Comment by Bien-CV** [comment]
Hi Lloyd, I can't get the use-case of this feature, could you explain further ?

**Comment by lloydwatkin** [comment]
I was planning on essentially white labelling the system so others could theme, but it's not necessary and more features are more important :)

**Comment by lloydwatkin** [comment]
In which case I'll close

**Comment by Bien-CV** [comment]
Okay thank you. We will work on re-building the CSS of the welcome page then, it's absent from the sources atm.
